openapi: 3.0.0
info:
  title: 'OpenApi Documentation'
  description: 'Документация для авто-сервиса'
  version: 1.0.0
paths:
  /calculate:
    post:
      tags:
        - id
      summary: 'calculate all services to the coefficients.'
      operationId: servicesId
      responses:
        '405':
          description: 'Invalid input'
  /Services/:
    get:
      tags:
        - Services
      summary: 'Получить список всех доступных сервисов'
      description: 'Получаем список всех доступных сервисов'
      operationId: getServices
      parameters:
        -
          name: tags
          in: query
          description: 'Параметры с Get, для этого запроса пока не принимаются на бэке, это образец'
          required: false
          style: form
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: 'successful operation'
        '401':
          description: Unauthenticated
        '403':
          description: Forbidden
  /TechServiceType:
    get:
      tags:
        - TechServiceType
      summary: 'Получить список всех доступных категорий сервисов'
      description: 'Получаем список всех доступных категорий сервисов'
      operationId: index
      responses:
        '200':
          description: 'successful operation'
        '401':
          description: Unauthenticated
        '403':
          description: Forbidden
  '/TechServiceType/{id}':
    get:
      tags:
        - 'TechServiceType by id'
      summary: 'Получить список сервисов выбранной категории'
      description: 'Получаем список сервисов выбранной категории'
      operationId: servicesTypeId
      parameters:
        -
          name: id
          in: path
          description: 'введите id необходимой категории'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'successful operation'
        '401':
          description: Unauthenticated
        '403':
          description: Forbidden
